//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyPhongMay_LichTH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public string Ma_admin { get; set; }
        public string Ten_admin { get; set; }
        public string Ma_tk { get; set; }
    
        public virtual UserLogin UserLogin { get; set; }
    }
}
