//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyPhongMay_LichTH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIAO_VIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GIAO_VIEN()
        {
            this.LOPs = new HashSet<LOP>();
            this.PhieuDangKyDayBus = new HashSet<PhieuDangKyDayBu>();
        }
    
        public string Ma_gv { get; set; }
        public string Ten_gv { get; set; }
        public string Gioi_tinh { get; set; }
        public Nullable<System.DateTime> Ngaysinh { get; set; }
        public string Ma_khoa { get; set; }
        public string Bo_mon { get; set; }
        public string Trinh_do { get; set; }
        public string Email { get; set; }
        public string So_dt { get; set; }
        public string Ma_tk { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOP> LOPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuDangKyDayBu> PhieuDangKyDayBus { get; set; }
        public virtual UserLogin UserLogin { get; set; }
        public virtual Khoa Khoa { get; set; }
    }
}
