//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyPhongMay_LichTH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOP()
        {
            this.LICHes = new HashSet<LICH>();
            this.LOP_SINHVIEN = new HashSet<LOP_SINHVIEN>();
            this.PhieuDangKyDayBus = new HashSet<PhieuDangKyDayBu>();
        }
    
        public string Ma_lop { get; set; }
        public string Ten_lop { get; set; }
        public string Ma_gv { get; set; }
        public string Ma_mon { get; set; }
        public string Hoc_ky { get; set; }
        public Nullable<int> So_sv { get; set; }
    
        public virtual GIAO_VIEN GIAO_VIEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LICH> LICHes { get; set; }
        public virtual MONHOC MONHOC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOP_SINHVIEN> LOP_SINHVIEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuDangKyDayBu> PhieuDangKyDayBus { get; set; }
    }
}
