//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyPhongMay_LichTH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOP_SINHVIEN
    {
        public int Id { get; set; }
        public string Ma_lop { get; set; }
        public string Ma_sv { get; set; }
    
        public virtual LOP LOP { get; set; }
        public virtual SINH_VIEN SINH_VIEN { get; set; }
    }
}
