//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyPhongMay_LichTH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MayTinh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MayTinh()
        {
            this.Histories = new HashSet<History>();
            this.Loi_Maytinh = new HashSet<Loi_Maytinh>();
            this.MayTinh_ThietBi = new HashSet<MayTinh_ThietBi>();
        }
    
        public string Ma_mt { get; set; }
        public string Ten_mt { get; set; }
        public string Cau_hinh { get; set; }
        public string Ma_phong { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> Ngay_them { get; set; }
        public string Brand { get; set; }
    
        public virtual Hang Hang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<History> Histories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Loi_Maytinh> Loi_Maytinh { get; set; }
        public virtual PHONG PHONG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MayTinh_ThietBi> MayTinh_ThietBi { get; set; }
    }
}
