//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyPhongMay_LichTH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MayTinh_ThietBi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MayTinh_ThietBi()
        {
            this.ThayTheThietBis = new HashSet<ThayTheThietBi>();
        }
    
        public int ID { get; set; }
        public string Ma_mt { get; set; }
        public string Ma_tb { get; set; }
        public Nullable<System.DateTime> TimeModified { get; set; }
    
        public virtual MayTinh MayTinh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThayTheThietBi> ThayTheThietBis { get; set; }
        public virtual ThietBi ThietBi { get; set; }
    }
}
