//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyPhongMay_LichTH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SINH_VIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SINH_VIEN()
        {
            this.LOP_SINHVIEN = new HashSet<LOP_SINHVIEN>();
            this.PhieuDangKyMuonMays = new HashSet<PhieuDangKyMuonMay>();
        }
    
        public string Ma_sv { get; set; }
        public string Ten_sv { get; set; }
        public string Gioi_tinh { get; set; }
        public Nullable<System.DateTime> Ngay_sinh { get; set; }
        public string Email { get; set; }
        public string So_dt { get; set; }
        public string Ma_tk { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOP_SINHVIEN> LOP_SINHVIEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuDangKyMuonMay> PhieuDangKyMuonMays { get; set; }
        public virtual UserLogin UserLogin { get; set; }
    }
}
