//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyPhongMay_LichTH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThayTheThietBi
    {
        public int ID { get; set; }
        public Nullable<int> Ma_mt_tb { get; set; }
        public Nullable<System.DateTime> Ngay_thay { get; set; }
        public string Ly_do { get; set; }
    
        public virtual MayTinh_ThietBi MayTinh_ThietBi { get; set; }
    }
}
