//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyPhongMay_LichTH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThietBi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThietBi()
        {
            this.Loi_Maytinh = new HashSet<Loi_Maytinh>();
            this.MayTinh_ThietBi = new HashSet<MayTinh_ThietBi>();
        }
    
        public string Ma_tb { get; set; }
        public string Ten_tb { get; set; }
        public string cau_hinh { get; set; }
        public string Ma_loai { get; set; }
        public Nullable<int> Ma_Nsx { get; set; }
        public string Ma_mt { get; set; }
        public string Mo_ta { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> isDeleted { get; set; }
        public Nullable<System.DateTime> Ngay_them { get; set; }
        public Nullable<int> StatusRepair { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual LoaiThietBi LoaiThietBi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Loi_Maytinh> Loi_Maytinh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MayTinh_ThietBi> MayTinh_ThietBi { get; set; }
    }
}
